server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/blog_auth
    username: postgres
    password: tushar123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: QWxhZGRpbjpPcGVuU2zzByUUnHHYW1lU2VjcmV0S2V5MTIzNDU2
  expiration-ms: 3600000    #1 hour


logging:
  level:
    root: INFO
    com.blogplatform.auth: INFO
    org.springframework.security: DEBUG